`timescale 1ns/1ps

// PCM-domain x2 decimation anti-alias for the native DSD path.
//
// dsd_to_pcm.v outputs 352.8 kHz pairs on a 128-MCLK grid. This stage
// decimates by 2 to the frozen 176.4 kHz (MCLK/256) output grid so the
// result feeds the same dither/I2S/TDA1541 chain as the NOS regime.
//
// Filter: 128-tap Kaiser (beta=12), Q31, DC sum = 2^31 (unity gain on
// the dsd_to_pcm output scale). Response (tools/gen_dsd_decim2_coeffs.py
// --check): flat to 20.5 kHz (0.003 dB ripple), -102 dB by 40 kHz,
// -145 dB at the 156.4 kHz fold band - the first-stage DSD-noise residue
// above the audio and the /2 aliases stay below the 16-bit floor for
// every DSD rate (64..512).
//
// MAC schedule (one tap per MCLK, address presented combinationally):
// ring slots are 7-bit; slot (q+k) holds x[2n-(128-k)], so slot (q+1) is
// x[2n-127] and slot q is x[2n]. After an EVEN input at posedge T:
//   T:     ring write x[2n] at q; base <= q; mac_cnt <= 1; acc <= 0
//   T+m:   read_addr = base + m   (m = 1..128, 7-bit wrap: q+1 .. q)
//          c_cur <= tap(128-m)    (tap 127 at m=1 .. tap 0 at m=128)
//          the SDPB registers mem[read_addr] at this posedge
//   T+m+1: acc += c_cur * hist    (hist = mem[read_addr of T+m]; the
//          pairing: tap(129-m) x x[2n-(129-m)] for m = 1..128)
// The odd input (T+128, same posedge as m=128) writes the slot q+1,
// which is read only at m=1, so the convolution is never disturbed.
// The result is latched at T+130 (acc complete after the m=128 product
// entered at the end of T+129). One output pair per 256 MCLK.
module dsd_pcm_decim2 (
    input  wire               clk,
    input  wire               rst_n,
    input  wire               in_valid,
    input  wire signed [31:0] in_l,
    input  wire signed [31:0] in_r,
    output reg                out_valid,
    output reg  signed [31:0] out_l,
    output reg  signed [31:0] out_r
);
    // Tap-select coefficient ROM.
    // Auto-generated by tools/gen_dsd_decim2_coeffs.py - do not edit.
function [31:0] DSD_DECIM2_TAP;
    input [6:0] t;
    begin
        case (t)
            7'd0: DSD_DECIM2_TAP = 32'h000001F6;
            7'd1: DSD_DECIM2_TAP = 32'h00000598;
            7'd2: DSD_DECIM2_TAP = 32'h00000959;
            7'd3: DSD_DECIM2_TAP = 32'h000008EC;
            7'd4: DSD_DECIM2_TAP = 32'hFFFFFE6D;
            7'd5: DSD_DECIM2_TAP = 32'hFFFFE55F;
            7'd6: DSD_DECIM2_TAP = 32'hFFFFBF46;
            7'd7: DSD_DECIM2_TAP = 32'hFFFF97E5;
            7'd8: DSD_DECIM2_TAP = 32'hFFFF863B;
            7'd9: DSD_DECIM2_TAP = 32'hFFFFA78A;
            7'd10: DSD_DECIM2_TAP = 32'h00001347;
            7'd11: DSD_DECIM2_TAP = 32'h0000CA6A;
            7'd12: DSD_DECIM2_TAP = 32'h0001A82D;
            7'd13: DSD_DECIM2_TAP = 32'h00025CFF;
            7'd14: DSD_DECIM2_TAP = 32'h00027BC0;
            7'd15: DSD_DECIM2_TAP = 32'h00019C6D;
            7'd16: DSD_DECIM2_TAP = 32'hFFFF8E96;
            7'd17: DSD_DECIM2_TAP = 32'hFFFC8BF1;
            7'd18: DSD_DECIM2_TAP = 32'hFFF9540A;
            7'd19: DSD_DECIM2_TAP = 32'hFFF71A81;
            7'd20: DSD_DECIM2_TAP = 32'hFFF73B97;
            7'd21: DSD_DECIM2_TAP = 32'hFFFABEE8;
            7'd22: DSD_DECIM2_TAP = 32'h0001C892;
            7'd23: DSD_DECIM2_TAP = 32'h000B2CCD;
            7'd24: DSD_DECIM2_TAP = 32'h00145F5A;
            7'd25: DSD_DECIM2_TAP = 32'h0019E77F;
            7'd26: DSD_DECIM2_TAP = 32'h00185A86;
            7'd27: DSD_DECIM2_TAP = 32'h000DAA1D;
            7'd28: DSD_DECIM2_TAP = 32'hFFFA6243;
            7'd29: DSD_DECIM2_TAP = 32'hFFE2586D;
            7'd30: DSD_DECIM2_TAP = 32'hFFCC5C5B;
            7'd31: DSD_DECIM2_TAP = 32'hFFC0B8CE;
            7'd32: DSD_DECIM2_TAP = 32'hFFC6B504;
            7'd33: DSD_DECIM2_TAP = 32'hFFE1B40A;
            7'd34: DSD_DECIM2_TAP = 32'h000EDF15;
            7'd35: DSD_DECIM2_TAP = 32'h004456D1;
            7'd36: DSD_DECIM2_TAP = 32'h00729F28;
            7'd37: DSD_DECIM2_TAP = 32'h00885DCF;
            7'd38: DSD_DECIM2_TAP = 32'h0077B997;
            7'd39: DSD_DECIM2_TAP = 32'h003BEBDE;
            7'd40: DSD_DECIM2_TAP = 32'hFFDD2BC4;
            7'd41: DSD_DECIM2_TAP = 32'hFF713B1B;
            7'd42: DSD_DECIM2_TAP = 32'hFF179A62;
            7'd43: DSD_DECIM2_TAP = 32'hFEF1A3B5;
            7'd44: DSD_DECIM2_TAP = 32'hFF183464;
            7'd45: DSD_DECIM2_TAP = 32'hFF91B322;
            7'd46: DSD_DECIM2_TAP = 32'h004BB838;
            7'd47: DSD_DECIM2_TAP = 32'h011B1EBC;
            7'd48: DSD_DECIM2_TAP = 32'h01C3CEFD;
            7'd49: DSD_DECIM2_TAP = 32'h02076F43;
            7'd50: DSD_DECIM2_TAP = 32'h01B7E877;
            7'd51: DSD_DECIM2_TAP = 32'h00C8FD93;
            7'd52: DSD_DECIM2_TAP = 32'hFF5BB051;
            7'd53: DSD_DECIM2_TAP = 32'hFDBF2465;
            7'd54: DSD_DECIM2_TAP = 32'hFC650DB5;
            7'd55: DSD_DECIM2_TAP = 32'hFBCAEE9A;
            7'd56: DSD_DECIM2_TAP = 32'hFC5CAB92;
            7'd57: DSD_DECIM2_TAP = 32'hFE575270;
            7'd58: DSD_DECIM2_TAP = 32'h01B3A2F2;
            7'd59: DSD_DECIM2_TAP = 32'h061E972B;
            7'd60: DSD_DECIM2_TAP = 32'h0B031002;
            7'd61: DSD_DECIM2_TAP = 32'h0FA3A0D6;
            7'd62: DSD_DECIM2_TAP = 32'h133F4F7E;
            7'd63: DSD_DECIM2_TAP = 32'h15391B8A;
            7'd64: DSD_DECIM2_TAP = 32'h15391B8A;
            7'd65: DSD_DECIM2_TAP = 32'h133F4F7E;
            7'd66: DSD_DECIM2_TAP = 32'h0FA3A0D6;
            7'd67: DSD_DECIM2_TAP = 32'h0B031002;
            7'd68: DSD_DECIM2_TAP = 32'h061E972B;
            7'd69: DSD_DECIM2_TAP = 32'h01B3A2F2;
            7'd70: DSD_DECIM2_TAP = 32'hFE575270;
            7'd71: DSD_DECIM2_TAP = 32'hFC5CAB92;
            7'd72: DSD_DECIM2_TAP = 32'hFBCAEE9A;
            7'd73: DSD_DECIM2_TAP = 32'hFC650DB5;
            7'd74: DSD_DECIM2_TAP = 32'hFDBF2465;
            7'd75: DSD_DECIM2_TAP = 32'hFF5BB051;
            7'd76: DSD_DECIM2_TAP = 32'h00C8FD93;
            7'd77: DSD_DECIM2_TAP = 32'h01B7E877;
            7'd78: DSD_DECIM2_TAP = 32'h02076F43;
            7'd79: DSD_DECIM2_TAP = 32'h01C3CEFD;
            7'd80: DSD_DECIM2_TAP = 32'h011B1EBC;
            7'd81: DSD_DECIM2_TAP = 32'h004BB838;
            7'd82: DSD_DECIM2_TAP = 32'hFF91B322;
            7'd83: DSD_DECIM2_TAP = 32'hFF183464;
            7'd84: DSD_DECIM2_TAP = 32'hFEF1A3B5;
            7'd85: DSD_DECIM2_TAP = 32'hFF179A62;
            7'd86: DSD_DECIM2_TAP = 32'hFF713B1B;
            7'd87: DSD_DECIM2_TAP = 32'hFFDD2BC4;
            7'd88: DSD_DECIM2_TAP = 32'h003BEBDE;
            7'd89: DSD_DECIM2_TAP = 32'h0077B997;
            7'd90: DSD_DECIM2_TAP = 32'h00885DCF;
            7'd91: DSD_DECIM2_TAP = 32'h00729F28;
            7'd92: DSD_DECIM2_TAP = 32'h004456D1;
            7'd93: DSD_DECIM2_TAP = 32'h000EDF15;
            7'd94: DSD_DECIM2_TAP = 32'hFFE1B40A;
            7'd95: DSD_DECIM2_TAP = 32'hFFC6B504;
            7'd96: DSD_DECIM2_TAP = 32'hFFC0B8CE;
            7'd97: DSD_DECIM2_TAP = 32'hFFCC5C5B;
            7'd98: DSD_DECIM2_TAP = 32'hFFE2586D;
            7'd99: DSD_DECIM2_TAP = 32'hFFFA6243;
            7'd100: DSD_DECIM2_TAP = 32'h000DAA1D;
            7'd101: DSD_DECIM2_TAP = 32'h00185A86;
            7'd102: DSD_DECIM2_TAP = 32'h0019E77F;
            7'd103: DSD_DECIM2_TAP = 32'h00145F5A;
            7'd104: DSD_DECIM2_TAP = 32'h000B2CCD;
            7'd105: DSD_DECIM2_TAP = 32'h0001C892;
            7'd106: DSD_DECIM2_TAP = 32'hFFFABEE8;
            7'd107: DSD_DECIM2_TAP = 32'hFFF73B97;
            7'd108: DSD_DECIM2_TAP = 32'hFFF71A81;
            7'd109: DSD_DECIM2_TAP = 32'hFFF9540A;
            7'd110: DSD_DECIM2_TAP = 32'hFFFC8BF1;
            7'd111: DSD_DECIM2_TAP = 32'hFFFF8E96;
            7'd112: DSD_DECIM2_TAP = 32'h00019C6D;
            7'd113: DSD_DECIM2_TAP = 32'h00027BC0;
            7'd114: DSD_DECIM2_TAP = 32'h00025CFF;
            7'd115: DSD_DECIM2_TAP = 32'h0001A82D;
            7'd116: DSD_DECIM2_TAP = 32'h0000CA6A;
            7'd117: DSD_DECIM2_TAP = 32'h00001347;
            7'd118: DSD_DECIM2_TAP = 32'hFFFFA78A;
            7'd119: DSD_DECIM2_TAP = 32'hFFFF863B;
            7'd120: DSD_DECIM2_TAP = 32'hFFFF97E5;
            7'd121: DSD_DECIM2_TAP = 32'hFFFFBF46;
            7'd122: DSD_DECIM2_TAP = 32'hFFFFE55F;
            7'd123: DSD_DECIM2_TAP = 32'hFFFFFE6D;
            7'd124: DSD_DECIM2_TAP = 32'h000008EC;
            7'd125: DSD_DECIM2_TAP = 32'h00000959;
            7'd126: DSD_DECIM2_TAP = 32'h00000598;
            7'd127: DSD_DECIM2_TAP = 32'h000001F6;
            default: DSD_DECIM2_TAP = 32'sd0;
        endcase
    end
endfunction

    reg [6:0] write_ptr;
    reg [6:0] mac_base;
    reg       pair_phase;       // 0 = even input (MAC start), 1 = odd
    reg [8:0] mac_cnt;          // 0 = idle; 1..129 = sweep; 130 = latch

    wire [6:0] read_addr = (mac_cnt == 9'd0) ? 7'd0
                           : mac_base + mac_cnt[6:0];

    wire signed [31:0] hist_l;
    wire signed [31:0] hist_r;

    hb_sample_ram #(
        .DEPTH(128),
        .ADDR_BITS(7)
    ) dl_l (
        .clk(clk),
        .write_en(in_valid),
        .write_addr(write_ptr),
        .read_addr(read_addr),
        .write_data(in_l),
        .read_data(hist_l)
    );

    hb_sample_ram #(
        .DEPTH(128),
        .ADDR_BITS(7)
    ) dl_r (
        .clk(clk),
        .write_en(in_valid),
        .write_addr(write_ptr),
        .read_addr(read_addr),
        .write_data(in_r),
        .read_data(hist_r)
    );

    reg signed [31:0] c_cur;
    reg signed [65:0] acc_l;
    reg signed [65:0] acc_r;
    // hist_* come out of the RAM as unsigned wires: force signed so the
    // negative Q31 coefficients do not poison the product.
    wire signed [63:0] prod_l = $signed(c_cur) * $signed(hist_l);
    wire signed [63:0] prod_r = $signed(c_cur) * $signed(hist_r);

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            write_ptr  <= 7'd0;
            mac_base   <= 7'd0;
            pair_phase <= 1'b0;
            mac_cnt    <= 9'd0;
            c_cur      <= 32'sd0;
            acc_l      <= 66'sd0;
            acc_r      <= 66'sd0;
            out_valid  <= 1'b0;
            out_l      <= 32'sd0;
            out_r      <= 32'sd0;
        end else begin
            out_valid <= 1'b0;

            // ---------------- ring write / MAC start ----------------
            if (in_valid) begin
                mac_base <= write_ptr;          // slot of this sample
                if (write_ptr == 7'd127)
                    write_ptr <= 7'd0;
                else
                    write_ptr <= write_ptr + 1'b1;

                if (!pair_phase && (mac_cnt == 9'd0)) begin
                    pair_phase <= 1'b1;
                    mac_cnt    <= 9'd1;
                    acc_l      <= 66'sd0;
                    acc_r      <= 66'sd0;
                end else if (pair_phase) begin
                    pair_phase <= 1'b0;
                end
            end

            // ---------------- MAC sweep (independent of in_valid) ----
            if (mac_cnt != 9'd0) begin
                if (mac_cnt == 9'd130) begin
                    // Sum complete (the tap-0 product entered acc at the
                    // end of cycle 129): latch the saturated result.
                    // NB: a part-select of a signed reg is unsigned, so
                    // the comparisons must force signedness explicitly.
                    mac_cnt <= 9'd0;
                    if ($signed(acc_l[65:31]) > 35'sd2147483647)
                        out_l <= 32'sh7fffffff;
                    else if ($signed(acc_l[65:31]) < -35'sd2147483648)
                        out_l <= 32'sh80000000;
                    else
                        out_l <= acc_l[62:31];
                    if ($signed(acc_r[65:31]) > 35'sd2147483647)
                        out_r <= 32'sh7fffffff;
                    else if ($signed(acc_r[65:31]) < -35'sd2147483648)
                        out_r <= 32'sh80000000;
                    else
                        out_r <= acc_r[62:31];
                    out_valid <= 1'b1;
                end else begin
                    // Coefficient for the tap presented this cycle (its
                    // product lands in acc next cycle). mac_cnt <= 128,
                    // so 128 - mac_cnt fits the 7-bit tap index.
                    if ((mac_cnt >= 9'd1) && (mac_cnt <= 9'd128))
                        c_cur <= DSD_DECIM2_TAP(9'd128 - mac_cnt);
                    // Product add: c_cur registered last cycle x the data
                    // for the address presented last cycle.
                    if ((mac_cnt >= 9'd2) && (mac_cnt <= 9'd129)) begin
                        acc_l <= acc_l + {{2{prod_l[63]}}, prod_l};
                        acc_r <= acc_r + {{2{prod_r[63]}}, prod_r};
                    end
                    mac_cnt <= mac_cnt + 1'b1;
                end
            end
        end
    end

endmodule
