// DSD (native, DSD64..DSD512) to PCM 352.8/384 kHz converter.
//
// The transport presents: the bit clock on the BCLK pin, DATA1 (left) on
// the SDATA pin, and DATA2 (right) either on the LRCLK pin (Amanero-style,
// the classic behavior) or on a dedicated pin (dsd_data2_alt). When DSD_ON
// rises, a ~1 ms acquisition window counts the transitions of the
// dedicated pin sampled only at DSD bit-clock boundaries: if the line
// carries a bit-correlated stream (>= 16 bit-boundary transitions) it is
// used as DATA2, otherwise the LRCLK pin is used. Activity between bit
// boundaries (crosstalk, glitches) is ignored. The decision is latched for
// the whole DSD session and re-armed only while DSD_ON is low.
//
// The bit-clock period (2/4/8/16 MCLK) is averaged over the first 256
// bits and selects the decimation (64/32/16/8 bits per output sample).
// The decimator is a 1024-tap windowed-sinc FIR at the output rate
// (352.8/384 kHz): passband flat to ~20 kHz, <= -40 dB by 22.05 kHz so
// the DSD64 modulator noise folding into the audio band stays below the
// 16-bit floor. The input is 1-bit, so each tap is just an add/subtract
// of its coefficient (no multipliers); 8 taps are processed per MCLK per
// channel, one output pair per 128 MCLK. Coefficients live in 8 SDPB
// blocks (mod-8 split, tools/dsd_coeff_params.vh), DC gain = 2^31.
//
// sample_valid is held low while dsd_on is low, during the acquisition
// window, and for the first frame after it.
module dsd_to_pcm (
    input  wire       mclk,
    input  wire       rst_n,
    input  wire       dsd_on,          // active high
    input  wire       dsd_clk_in,      // DSD bit clock (BCLK pin)
    input  wire       dsd_data1,       // DATA1 / left (SDATA pin)
    input  wire       dsd_data2_alt,   // dedicated DATA2 pin (transport 2)
    input  wire       lrck_in,         // LRCLK pin (Amanero-style DATA2)
    output reg        sample_valid,
    output reg  signed [31:0] sample_l,
    output reg  signed [31:0] sample_r
);
    localparam [31:0] ACQ_CYCLES = 32'd45000;   // ~1 ms at 45.1584 MHz
    localparam [15:0] ALT_THRESH = 16'd16;      // min transitions to use alt
    localparam integer TAPS = 1024;

    // Coefficient storage: 128 words per SDPB block, 8 blocks.
    // Auto-generated by tools/gen_dsd_coeffs.py - do not edit.
localparam [255:0] DSD_B0_00 = 256'h00000C02000008CA000004F9000001ED00000023FFFFFF76FFFFFF79FFFFFFBB;
localparam [255:0] DSD_B0_01 = 256'hFFFFB650FFFFAADBFFFFB653FFFFCD8DFFFFE69BFFFFFAD70000075F00000C68;
localparam [255:0] DSD_B0_02 = 256'h00003D600001059500015BBC00014F1C0001007B0000958F00002ED7FFFFE195;
localparam [255:0] DSD_B0_03 = 256'h000365ECFFFFF488FFFD5E32FFFBF779FFFBBF72FFFC7467FFFDB231FFFF10FF;
localparam [255:0] DSD_B0_04 = 256'hFFEE0B10FFF6191DFFFE73E20005554C0009A43E000B0CA00009E82700070639;
localparam [255:0] DSD_B0_05 = 256'h003313DA00293D6A00191647000711FFFFF72B38FFEC2CB6FFE758A8FFE87080;
localparam [255:0] DSD_B0_06 = 256'hFF928EBAFF8E97A8FFA18978FFC2CD7AFFE91571000C0B6400259BCE0032A843;
localparam [255:0] DSD_B0_07 = 256'h02483680020B295701ACCE540139B64000C0953B004FE076FFF39410FFB38671;
localparam [255:0] DSD_B0_08 = 256'hFFE9EB540043048100B1C19A012A9799019F43470200F6BF0242BCDB025BA18B;
localparam [255:0] DSD_B0_09 = 256'h0027F447000FD905FFEDC930FFC78002FFA51A74FF8FDDE8FF909147FFADB3AD;
localparam [255:0] DSD_B0_0A = 256'hFFE72DC2FFEB39B0FFF57C2C0004E5660016D8DE002779B4003256BD00335F5E;
localparam [255:0] DSD_B0_0B = 256'h00099F36000B085F0009F98D000606C8FFFF6C53FFF72AEBFFEEF622FFE8EE7B;
localparam [255:0] DSD_B0_0C = 256'hFFFDDE39FFFC96DBFFFBCAF5FFFBE0C1FFFD2001FFFF93260002F0E200069752;
localparam [255:0] DSD_B0_0D = 256'h0000237E000087EF0000F3E90001481E00015F000001168400005C7FFFFF3AAD;
localparam [255:0] DSD_B0_0E = 256'h00000861FFFFFCD9FFFFE97EFFFFD0C1FFFFB8CFFFFFAB42FFFFB347FFFFDA45;
localparam [255:0] DSD_B0_0F = 256'hFFFFFF80FFFFFF7000000000000001A2000004880000084F00000BB500000C9A;
localparam [255:0] DSD_B1_00 = 256'h00000C44000009430000056D0000023E0000004BFFFFFF80FFFFFF73FFFFFFB3;
localparam [255:0] DSD_B1_01 = 256'hFFFFB9DBFFFFAAD0FFFFB404FFFFCA5EFFFFE3A3FFFFF8B50000063E00000C20;
localparam [255:0] DSD_B1_02 = 256'h00001CA40000F2D5000156E70001551100010C9D0000A34500003A99FFFFE970;
localparam [255:0] DSD_B1_03 = 256'h0003DBC800005974FFFDA13EFFFC1301FFFBB7ADFFFC5418FFFD86A7FFFEE67C;
localparam [255:0] DSD_B1_04 = 256'hFFED29D3FFF50861FFFD7550000499430009431B000B0686000A2A140007722D;
localparam [255:0] DSD_B1_05 = 256'h0033A76A002AE7B4001B4C6500094777FFF8EE69FFED38E7FFE79BA3FFE804C6;
localparam [255:0] DSD_B1_06 = 256'hFF950187FF8DADE1FF9E3200FFBE2EAAFFE453A60008172D002310430031BDD0;
localparam [255:0] DSD_B1_07 = 256'h024D07B60214D54C01BA05B60148BCD900CF8B63005D0F72FFFDAF74FFB9D735;
localparam [255:0] DSD_B1_08 = 256'hFFE0B7D10036808F00A31748011B687801916BBB01F6431A023C9DD6025AEE3F;
localparam [255:0] DSD_B1_09 = 256'h002A18FF00137DD0FFF26B3AFFCC41B4FFA8E03CFF917CA9FF8F06DAFFA85EDE;
localparam [255:0] DSD_B1_0A = 256'hFFE71A6CFFEA6004FFF3E2420002C3630014966000259ECF003171D30033E3DD;
localparam [255:0] DSD_B1_0B = 256'h00094FBC000AFA1A000A43130006AD6300005DEBFFF83CC5FFEFE9E9FFE97DC3;
localparam [255:0] DSD_B1_0C = 256'hFFFE0A8DFFFCBB3CFFFBDA0AFFFBCEC3FFFCE6BBFFFF358C00027D13000625FA;
localparam [255:0] DSD_B1_0D = 256'h0000189700007A700000E6FB00014029000160C2000125A3000079F2FFFF6364;
localparam [255:0] DSD_B1_0E = 256'h00000946FFFFFEBBFFFFEC4BFFFFD3F8FFFFBB75FFFFAC00FFFFB0BCFFFFD382;
localparam [255:0] DSD_B1_0F = 256'hFFFFFF87FFFFFF6BFFFFFFE10000015C0000041B000007D300000B5F00000CB7;
localparam [255:0] DSD_B2_00 = 256'h00000C79000009B9000005E50000029400000078FFFFFF8CFFFFFF6EFFFFFFAA;
localparam [255:0] DSD_B2_01 = 256'hFFFFBDEAFFFFAB27FFFFB1EAFFFFC73BFFFFE09AFFFFF674000004FE00000BC1;
localparam [255:0] DSD_B2_02 = 256'hFFFFFA5C0000DE4100015074000159E90001183D0000B101000046BEFFFFF1D5;
localparam [255:0] DSD_B2_03 = 256'h000452090000C1A6FFFDE910FFFC336CFFFBB3D4FFFC3623FFFD5BCBFFFEBB47;
localparam [255:0] DSD_B2_04 = 256'hFFEC5388FFF3F9C1FFFC71610003D30F0008D621000AF5C3000A64800007DAAB;
localparam [255:0] DSD_B2_05 = 256'h00340FC3002C765B001D78FF000B8400FFFAC4ADFFEE5DFDFFE7F720FFE7AC39;
localparam [255:0] DSD_B2_06 = 256'hFF97EBC1FF8D245FFF9B18B9FFB9A837FFDF879B0003FED10020528300309F70;
localparam [255:0] DSD_B2_07 = 256'h02512DCE021DF54E01C6E2630157A3CE00DE9D21006A8C3500083AA2FFC0A5AF;
localparam [255:0] DSD_B2_08 = 256'hFFD7FBC1002A595500949CE0010C306901834EFB01EB14400235DCD90259880C;
localparam [255:0] DSD_B2_09 = 256'h002C097B0016F7B8FFF6F810FFD10E0FFFACD610FF936FD0FF8DECDEFFA387AC;
localparam [255:0] DSD_B2_0A = 256'hFFE71E15FFE99FC7FFF25E5A0000AD9A001250F30023AF03003066F6003436A6;
localparam [255:0] DSD_B2_0B = 256'h0008FA3C000AE22D000A80E8000748D5000147FEFFF94DAFFFF0E546FFEA1D58;
localparam [255:0] DSD_B2_0C = 256'hFFFE36FEFFFCE154FFFBEC7FFFFBC165FFFCB26DFFFEDBF300020AE20005B2B0;
localparam [255:0] DSD_B2_0D = 256'h00000E2800006D200000D9C20001375200016110000132F7000095AFFFFF8B06;
localparam [255:0] DSD_B2_0E = 256'h00000A0D0000007DFFFFEEFEFFFFD72CFFFFBE3EFFFFAD0FFFFFAEABFFFFCD4B;
localparam [255:0] DSD_B2_0F = 256'hFFFFFF8FFFFFFF69FFFFFFC60000011B000003B30000075600000AFF00000CC1;
localparam [255:0] DSD_B3_00 = 256'h00000CA100000A2C0000065E000002EE000000A9FFFFFF9CFFFFFF6BFFFFFFA1;
localparam [255:0] DSD_B3_01 = 256'hFFFFC280FFFFABE5FFFFB00AFFFFC426FFFFDD80FFFFF4140000039E00000B4A;
localparam [255:0] DSD_B3_02 = 256'hFFFFD69B0000C7DD0001485700015D93000123480000BEB40000533CFFFFFAC2;
localparam [255:0] DSD_B3_03 = 256'h0004C83E00012CD5FFFE358BFFFC58C7FFFBB411FFFC1AC0FFFD31D1FFFE8F86;
localparam [255:0] DSD_B3_04 = 256'hFFEB894CFFF2EE4DFFFB68E40003031E00085D5C000ADA10000A96F400083F30;
localparam [255:0] DSD_B3_05 = 256'h00344B5A002DE730001F99D1000DC5BBFFFCACD4FFEF9B97FFE86B7AFFE767B8;
localparam [255:0] DSD_B3_06 = 256'hFF9B4F37FF8CFEC5FF984240FFB53ECFFFDAB542FFFFC4F0001D63A1002F4CB9;
localparam [255:0] DSD_B3_07 = 256'h0254A6750226845401D35D7A0166638400EDC3600078513E00133265FFC7F146;
localparam [255:0] DSD_B3_08 = 256'hFFCFB90C001E933C008658CB00FCF6E90174F46B01DF7045022E7DA602576FB9;
localparam [255:0] DSD_B3_09 = 256'h002DC56D001A44E1FFFB6C5BFFD5E0AEFFB0F72DFF95B321FF8D4085FF9F2D71;
localparam [255:0] DSD_B3_0A = 256'hFFE73815FFE8F8F7FFF0F13DFFFEA59800100AB70021AC95002F3815003458C0;
localparam [255:0] DSD_B3_0B = 256'h00089F37000AC0FE000AB32E0007D8E2000229EBFFFA5CB3FFF1E71CFFEACC35;
localparam [255:0] DSD_B3_0C = 256'hFFFE635FFFFD08EDFFFC0222FFFBB88BFFFC831BFFFE868F00019AAF00053DF4;
localparam [255:0] DSD_B3_0D = 256'h000004340000600B0000CC4F00012DAB00015FFB00013E850000AFAAFFFFB177;
localparam [255:0] DSD_B3_0E = 256'h00000AB90000021DFFFFF197FFFFDA5BFFFFC126FFFFAE6AFFFFAD0FFFFFC7A0;
localparam [255:0] DSD_B3_0F = 256'hFFFFFF98FFFFFF69FFFFFFAF000000DF0000034E000006D900000A9800000CB9;
localparam [255:0] DSD_B4_00 = 256'h00000CB900000A98000006D90000034E000000DFFFFFFFAFFFFFFF69FFFFFF98;
localparam [255:0] DSD_B4_01 = 256'hFFFFC7A0FFFFAD0FFFFFAE6AFFFFC126FFFFDA5BFFFFF1970000021D00000AB9;
localparam [255:0] DSD_B4_02 = 256'hFFFFB1770000AFAA00013E8500015FFB00012DAB0000CC4F0000600B00000434;
localparam [255:0] DSD_B4_03 = 256'h00053DF400019AAFFFFE868FFFFC831BFFFBB88BFFFC0222FFFD08EDFFFE635F;
localparam [255:0] DSD_B4_04 = 256'hFFEACC35FFF1E71CFFFA5CB3000229EB0007D8E2000AB32E000AC0FE00089F37;
localparam [255:0] DSD_B4_05 = 256'h003458C0002F38150021AC9500100AB7FFFEA598FFF0F13DFFE8F8F7FFE73815;
localparam [255:0] DSD_B4_06 = 256'hFF9F2D71FF8D4085FF95B321FFB0F72DFFD5E0AEFFFB6C5B001A44E1002DC56D;
localparam [255:0] DSD_B4_07 = 256'h02576FB9022E7DA601DF70450174F46B00FCF6E9008658CB001E933CFFCFB90C;
localparam [255:0] DSD_B4_08 = 256'hFFC7F146001332650078513E00EDC3600166638401D35D7A022684540254A675;
localparam [255:0] DSD_B4_09 = 256'h002F4CB9001D63A1FFFFC4F0FFDAB542FFB53ECFFF984240FF8CFEC5FF9B4F37;
localparam [255:0] DSD_B4_0A = 256'hFFE767B8FFE86B7AFFEF9B97FFFCACD4000DC5BB001F99D1002DE73000344B5A;
localparam [255:0] DSD_B4_0B = 256'h00083F30000A96F4000ADA1000085D5C0003031EFFFB68E4FFF2EE4DFFEB894C;
localparam [255:0] DSD_B4_0C = 256'hFFFE8F86FFFD31D1FFFC1AC0FFFBB411FFFC58C7FFFE358B00012CD50004C83E;
localparam [255:0] DSD_B4_0D = 256'hFFFFFAC20000533C0000BEB40001234800015D93000148570000C7DDFFFFD69B;
localparam [255:0] DSD_B4_0E = 256'h00000B4A0000039EFFFFF414FFFFDD80FFFFC426FFFFB00AFFFFABE5FFFFC280;
localparam [255:0] DSD_B4_0F = 256'hFFFFFFA1FFFFFF6BFFFFFF9C000000A9000002EE0000065E00000A2C00000CA1;
localparam [255:0] DSD_B5_00 = 256'h00000CC100000AFF00000756000003B30000011BFFFFFFC6FFFFFF69FFFFFF8F;
localparam [255:0] DSD_B5_01 = 256'hFFFFCD4BFFFFAEABFFFFAD0FFFFFBE3EFFFFD72CFFFFEEFE0000007D00000A0D;
localparam [255:0] DSD_B5_02 = 256'hFFFF8B06000095AF000132F700016110000137520000D9C200006D2000000E28;
localparam [255:0] DSD_B5_03 = 256'h0005B2B000020AE2FFFEDBF3FFFCB26DFFFBC165FFFBEC7FFFFCE154FFFE36FE;
localparam [255:0] DSD_B5_04 = 256'hFFEA1D58FFF0E546FFF94DAF000147FE000748D5000A80E8000AE22D0008FA3C;
localparam [255:0] DSD_B5_05 = 256'h003436A6003066F60023AF03001250F30000AD9AFFF25E5AFFE99FC7FFE71E15;
localparam [255:0] DSD_B5_06 = 256'hFFA387ACFF8DECDEFF936FD0FFACD610FFD10E0FFFF6F8100016F7B8002C097B;
localparam [255:0] DSD_B5_07 = 256'h0259880C0235DCD901EB144001834EFB010C306900949CE0002A5955FFD7FBC1;
localparam [255:0] DSD_B5_08 = 256'hFFC0A5AF00083AA2006A8C3500DE9D210157A3CE01C6E263021DF54E02512DCE;
localparam [255:0] DSD_B5_09 = 256'h00309F70002052830003FED1FFDF879BFFB9A837FF9B18B9FF8D245FFF97EBC1;
localparam [255:0] DSD_B5_0A = 256'hFFE7AC39FFE7F720FFEE5DFDFFFAC4AD000B8400001D78FF002C765B00340FC3;
localparam [255:0] DSD_B5_0B = 256'h0007DAAB000A6480000AF5C30008D6210003D30FFFFC7161FFF3F9C1FFEC5388;
localparam [255:0] DSD_B5_0C = 256'hFFFEBB47FFFD5BCBFFFC3623FFFBB3D4FFFC336CFFFDE9100000C1A600045209;
localparam [255:0] DSD_B5_0D = 256'hFFFFF1D5000046BE0000B1010001183D000159E9000150740000DE41FFFFFA5C;
localparam [255:0] DSD_B5_0E = 256'h00000BC1000004FEFFFFF674FFFFE09AFFFFC73BFFFFB1EAFFFFAB27FFFFBDEA;
localparam [255:0] DSD_B5_0F = 256'hFFFFFFAAFFFFFF6EFFFFFF8C0000007800000294000005E5000009B900000C79;
localparam [255:0] DSD_B6_00 = 256'h00000CB700000B5F000007D30000041B0000015CFFFFFFE1FFFFFF6BFFFFFF87;
localparam [255:0] DSD_B6_01 = 256'hFFFFD382FFFFB0BCFFFFAC00FFFFBB75FFFFD3F8FFFFEC4BFFFFFEBB00000946;
localparam [255:0] DSD_B6_02 = 256'hFFFF6364000079F2000125A3000160C2000140290000E6FB00007A7000001897;
localparam [255:0] DSD_B6_03 = 256'h000625FA00027D13FFFF358CFFFCE6BBFFFBCEC3FFFBDA0AFFFCBB3CFFFE0A8D;
localparam [255:0] DSD_B6_04 = 256'hFFE97DC3FFEFE9E9FFF83CC500005DEB0006AD63000A4313000AFA1A00094FBC;
localparam [255:0] DSD_B6_05 = 256'h0033E3DD003171D300259ECF001496600002C363FFF3E242FFEA6004FFE71A6C;
localparam [255:0] DSD_B6_06 = 256'hFFA85EDEFF8F06DAFF917CA9FFA8E03CFFCC41B4FFF26B3A00137DD0002A18FF;
localparam [255:0] DSD_B6_07 = 256'h025AEE3F023C9DD601F6431A01916BBB011B687800A317480036808FFFE0B7D1;
localparam [255:0] DSD_B6_08 = 256'hFFB9D735FFFDAF74005D0F7200CF8B630148BCD901BA05B60214D54C024D07B6;
localparam [255:0] DSD_B6_09 = 256'h0031BDD0002310430008172DFFE453A6FFBE2EAAFF9E3200FF8DADE1FF950187;
localparam [255:0] DSD_B6_0A = 256'hFFE804C6FFE79BA3FFED38E7FFF8EE6900094777001B4C65002AE7B40033A76A;
localparam [255:0] DSD_B6_0B = 256'h0007722D000A2A14000B06860009431B00049943FFFD7550FFF50861FFED29D3;
localparam [255:0] DSD_B6_0C = 256'hFFFEE67CFFFD86A7FFFC5418FFFBB7ADFFFC1301FFFDA13E000059740003DBC8;
localparam [255:0] DSD_B6_0D = 256'hFFFFE97000003A990000A34500010C9D00015511000156E70000F2D500001CA4;
localparam [255:0] DSD_B6_0E = 256'h00000C200000063EFFFFF8B5FFFFE3A3FFFFCA5EFFFFB404FFFFAAD0FFFFB9DB;
localparam [255:0] DSD_B6_0F = 256'hFFFFFFB3FFFFFF73FFFFFF800000004B0000023E0000056D0000094300000C44;
localparam [255:0] DSD_B7_00 = 256'h00000C9A00000BB50000084F00000488000001A200000000FFFFFF70FFFFFF80;
localparam [255:0] DSD_B7_01 = 256'hFFFFDA45FFFFB347FFFFAB42FFFFB8CFFFFFD0C1FFFFE97EFFFFFCD900000861;
localparam [255:0] DSD_B7_02 = 256'hFFFF3AAD00005C7F0001168400015F000001481E0000F3E9000087EF0000237E;
localparam [255:0] DSD_B7_03 = 256'h000697520002F0E2FFFF9326FFFD2001FFFBE0C1FFFBCAF5FFFC96DBFFFDDE39;
localparam [255:0] DSD_B7_04 = 256'hFFE8EE7BFFEEF622FFF72AEBFFFF6C53000606C80009F98D000B085F00099F36;
localparam [255:0] DSD_B7_05 = 256'h00335F5E003256BD002779B40016D8DE0004E566FFF57C2CFFEB39B0FFE72DC2;
localparam [255:0] DSD_B7_06 = 256'hFFADB3ADFF909147FF8FDDE8FFA51A74FFC78002FFEDC930000FD9050027F447;
localparam [255:0] DSD_B7_07 = 256'h025BA1910242BCDB0200F6BF019F4347012A979900B1C19A00430481FFE9EB54;
localparam [255:0] DSD_B7_08 = 256'hFFB38671FFF39410004FE07600C0953B0139B64001ACCE54020B295702483680;
localparam [255:0] DSD_B7_09 = 256'h0032A84300259BCE000C0B64FFE91571FFC2CD7AFFA18978FF8E97A8FF928EBA;
localparam [255:0] DSD_B7_0A = 256'hFFE87080FFE758A8FFEC2CB6FFF72B38000711FF0019164700293D6A003313DA;
localparam [255:0] DSD_B7_0B = 256'h000706390009E827000B0CA00009A43E0005554CFFFE73E2FFF6191DFFEE0B10;
localparam [255:0] DSD_B7_0C = 256'hFFFF10FFFFFDB231FFFC7467FFFBBF72FFFBF779FFFD5E32FFFFF488000365EC;
localparam [255:0] DSD_B7_0D = 256'hFFFFE19500002ED70000958F0001007B00014F1C00015BBC0001059500003D60;
localparam [255:0] DSD_B7_0E = 256'h00000C680000075FFFFFFAD7FFFFE69BFFFFCD8DFFFFB653FFFFAADBFFFFB650;
localparam [255:0] DSD_B7_0F = 256'hFFFFFFBBFFFFFF79FFFFFF7600000023000001ED000004F9000008CA00000C02;

    // ---------------- input synchronization (MCLK domain) ----------------
    reg [1:0] clk_sync;
    reg [1:0] d1_sync;
    reg [1:0] d2_sync;
    reg [1:0] lr_sync;
    reg [1:0] on_sync;

    always @(posedge mclk or negedge rst_n) begin
        if (!rst_n) begin
            clk_sync <= 2'b00;
            d1_sync  <= 2'b00;
            d2_sync  <= 2'b00;
            lr_sync  <= 2'b00;
            on_sync  <= 2'b00;
        end else begin
            clk_sync <= {clk_sync[0], dsd_clk_in};
            d1_sync  <= {d1_sync[0], dsd_data1};
            d2_sync  <= {d2_sync[0], dsd_data2_alt};
            lr_sync  <= {lr_sync[0], lrck_in};
            on_sync  <= {on_sync[0], dsd_on};
        end
    end

    wire dsd_active = on_sync[1];
    wire bit_en = !clk_sync[1] && clk_sync[0];   // rising edge of the bit clock

    // ---------------- acquisition: DATA2 source + rate ----------------
    reg        decide_done;
    reg        use_alt;
    reg [1:0]  decim_sel;      // 0: /8, 1: /16, 2: /32, 3: /64 (informative)
    reg [31:0] acq_cnt;
    reg [15:0] alt_trans;
    // Alternate DATA2 activity is evaluated at DSD bit boundaries. Counting
    // transitions between bit boundaries would mistake crosstalk or a
    // glitching, unrelated signal for a valid DATA2 stream.
    reg        d2_bit_prev;
    reg        d2_bit_seen;
    reg [7:0]  bit_no;
    reg [15:0] period_cnt;
    reg [15:0] period_sum;

    always @(posedge mclk or negedge rst_n) begin
        if (!rst_n) begin
            decide_done <= 1'b0;
            use_alt <= 1'b0;
            decim_sel <= 2'd0;
            acq_cnt <= 32'd0;
            alt_trans <= 16'd0;
            d2_bit_prev <= 1'b0;
            d2_bit_seen <= 1'b0;
            bit_no <= 8'd0;
            period_cnt <= 16'd0;
            period_sum <= 16'd0;
        end else begin
            if (!dsd_active) begin
                // Idle: reset the acquisition for the next DSD session.
                decide_done <= 1'b0;
                use_alt <= 1'b0;
                acq_cnt <= 32'd0;
                alt_trans <= 16'd0;
                d2_bit_prev <= d2_sync[1];
                d2_bit_seen <= 1'b0;
                bit_no <= 8'd0;
                period_cnt <= 16'd0;
                period_sum <= 16'd0;
            end else begin
                if (acq_cnt != ACQ_CYCLES)
                    acq_cnt <= acq_cnt + 32'd1;

                if (!decide_done && (acq_cnt == ACQ_CYCLES)) begin
                    decide_done <= 1'b1;
                    use_alt <= (alt_trans >= ALT_THRESH);
                    // Averaged bit period -> decimation factor.
                    if (period_sum <= 32'd768)
                        decim_sel <= 2'd3;      // 2 MCLK  -> DSD512 (/64)
                    else if (period_sum <= 32'd1536)
                        decim_sel <= 2'd2;      // 4 MCLK  -> DSD256 (/32)
                    else if (period_sum <= 32'd3072)
                        decim_sel <= 2'd1;      // 8 MCLK  -> DSD128 (/16)
                    else
                        decim_sel <= 2'd0;      // 16 MCLK -> DSD64  (/8)
                end

                // DATA2 transition count (only while deciding). Sample only
                // at DSD bit boundaries so activity between bits is ignored.
                if (bit_en) begin
                    if (!d2_bit_seen) begin
                        d2_bit_prev <= d2_sync[1];
                        d2_bit_seen <= 1'b1;
                    end else begin
                        if (d2_sync[1] != d2_bit_prev) begin
                            d2_bit_prev <= d2_sync[1];
                            if (!decide_done && (alt_trans != 16'hffff))
                                alt_trans <= alt_trans + 16'd1;
                        end
                    end
                end

                // Bit period accumulation over the first 256 bits.
                if (bit_en) begin
                    if (bit_no != 8'hff)
                        bit_no <= bit_no + 8'd1;
                    if ((bit_no < 8'd255) && (period_sum < 16'hffff))
                        period_sum <= period_sum + period_cnt;
                    period_cnt <= 16'd1;
                end else if (period_cnt != 16'hffff) begin
                    period_cnt <= period_cnt + 16'd1;
                end
            end
        end
    end

    // ---------------- 1-bit delay lines (1024 stages each) ----------------
    reg [TAPS-1:0] sr_l;
    reg [TAPS-1:0] sr_r;
    // The accumulator spans 128 MCLK cycles. Keep its input window fixed for
    // that interval; otherwise the live shift register advances while the
    // tap sweep is in progress and the result is not a convolution.
    reg [TAPS-1:0] fir_sr_l;
    reg [TAPS-1:0] fir_sr_r;

    always @(posedge mclk or negedge rst_n) begin
        if (!rst_n) begin
            sr_l <= {TAPS{1'b0}};
            sr_r <= {TAPS{1'b0}};
        end else if (bit_en && dsd_active) begin
            sr_l <= {sr_l[TAPS-2:0], d1_sync[1]};
            sr_r <= {sr_r[TAPS-2:0], use_alt ? d2_sync[1] : lr_sync[1]};
        end
    end

    // ---------------- coefficient storage: 8 SDPB blocks ----------------
    // Block j holds coeff[j + 8i], i = 0..127 (one read port each); the
    // tap group 8k..8k+7 is read from the word k of every block.
    reg [6:0]  tapk;
    reg [9:0]  tap_base;    // (previous tapk) * 8: aligns the 1-cycle RAM latency
    wire [13:0] ram_b = {2'd0, tapk, 5'd0};      // read word = tapk

    wire [31:0] csel0, csel1, csel2, csel3, csel4, csel5, csel6, csel7;

    SDPB #(
        .INIT_RAM_00(DSD_B0_00), .INIT_RAM_01(DSD_B0_01), .INIT_RAM_02(DSD_B0_02),
        .INIT_RAM_03(DSD_B0_03), .INIT_RAM_04(DSD_B0_04), .INIT_RAM_05(DSD_B0_05),
        .INIT_RAM_06(DSD_B0_06), .INIT_RAM_07(DSD_B0_07), .INIT_RAM_08(DSD_B0_08),
        .INIT_RAM_09(DSD_B0_09), .INIT_RAM_0A(DSD_B0_0A), .INIT_RAM_0B(DSD_B0_0B),
        .INIT_RAM_0C(DSD_B0_0C), .INIT_RAM_0D(DSD_B0_0D), .INIT_RAM_0E(DSD_B0_0E),
        .INIT_RAM_0F(DSD_B0_0F)
    ) cb0 (
        .DO(csel0), .DI(32'd0), .BLKSELA(3'd0), .BLKSELB(3'd0),
        .ADA(14'd0), .ADB(ram_b),
        .CLKA(mclk), .CLKB(mclk), .CEA(1'b0), .CEB(1'b1),
        .OCE(1'b1), .RESET(1'b0)
    );

    SDPB #(
        .INIT_RAM_00(DSD_B1_00), .INIT_RAM_01(DSD_B1_01), .INIT_RAM_02(DSD_B1_02),
        .INIT_RAM_03(DSD_B1_03), .INIT_RAM_04(DSD_B1_04), .INIT_RAM_05(DSD_B1_05),
        .INIT_RAM_06(DSD_B1_06), .INIT_RAM_07(DSD_B1_07), .INIT_RAM_08(DSD_B1_08),
        .INIT_RAM_09(DSD_B1_09), .INIT_RAM_0A(DSD_B1_0A), .INIT_RAM_0B(DSD_B1_0B),
        .INIT_RAM_0C(DSD_B1_0C), .INIT_RAM_0D(DSD_B1_0D), .INIT_RAM_0E(DSD_B1_0E),
        .INIT_RAM_0F(DSD_B1_0F)
    ) cb1 (
        .DO(csel1), .DI(32'd0), .BLKSELA(3'd0), .BLKSELB(3'd0),
        .ADA(14'd0), .ADB(ram_b),
        .CLKA(mclk), .CLKB(mclk), .CEA(1'b0), .CEB(1'b1),
        .OCE(1'b1), .RESET(1'b0)
    );

    SDPB #(
        .INIT_RAM_00(DSD_B2_00), .INIT_RAM_01(DSD_B2_01), .INIT_RAM_02(DSD_B2_02),
        .INIT_RAM_03(DSD_B2_03), .INIT_RAM_04(DSD_B2_04), .INIT_RAM_05(DSD_B2_05),
        .INIT_RAM_06(DSD_B2_06), .INIT_RAM_07(DSD_B2_07), .INIT_RAM_08(DSD_B2_08),
        .INIT_RAM_09(DSD_B2_09), .INIT_RAM_0A(DSD_B2_0A), .INIT_RAM_0B(DSD_B2_0B),
        .INIT_RAM_0C(DSD_B2_0C), .INIT_RAM_0D(DSD_B2_0D), .INIT_RAM_0E(DSD_B2_0E),
        .INIT_RAM_0F(DSD_B2_0F)
    ) cb2 (
        .DO(csel2), .DI(32'd0), .BLKSELA(3'd0), .BLKSELB(3'd0),
        .ADA(14'd0), .ADB(ram_b),
        .CLKA(mclk), .CLKB(mclk), .CEA(1'b0), .CEB(1'b1),
        .OCE(1'b1), .RESET(1'b0)
    );

    SDPB #(
        .INIT_RAM_00(DSD_B3_00), .INIT_RAM_01(DSD_B3_01), .INIT_RAM_02(DSD_B3_02),
        .INIT_RAM_03(DSD_B3_03), .INIT_RAM_04(DSD_B3_04), .INIT_RAM_05(DSD_B3_05),
        .INIT_RAM_06(DSD_B3_06), .INIT_RAM_07(DSD_B3_07), .INIT_RAM_08(DSD_B3_08),
        .INIT_RAM_09(DSD_B3_09), .INIT_RAM_0A(DSD_B3_0A), .INIT_RAM_0B(DSD_B3_0B),
        .INIT_RAM_0C(DSD_B3_0C), .INIT_RAM_0D(DSD_B3_0D), .INIT_RAM_0E(DSD_B3_0E),
        .INIT_RAM_0F(DSD_B3_0F)
    ) cb3 (
        .DO(csel3), .DI(32'd0), .BLKSELA(3'd0), .BLKSELB(3'd0),
        .ADA(14'd0), .ADB(ram_b),
        .CLKA(mclk), .CLKB(mclk), .CEA(1'b0), .CEB(1'b1),
        .OCE(1'b1), .RESET(1'b0)
    );

    SDPB #(
        .INIT_RAM_00(DSD_B4_00), .INIT_RAM_01(DSD_B4_01), .INIT_RAM_02(DSD_B4_02),
        .INIT_RAM_03(DSD_B4_03), .INIT_RAM_04(DSD_B4_04), .INIT_RAM_05(DSD_B4_05),
        .INIT_RAM_06(DSD_B4_06), .INIT_RAM_07(DSD_B4_07), .INIT_RAM_08(DSD_B4_08),
        .INIT_RAM_09(DSD_B4_09), .INIT_RAM_0A(DSD_B4_0A), .INIT_RAM_0B(DSD_B4_0B),
        .INIT_RAM_0C(DSD_B4_0C), .INIT_RAM_0D(DSD_B4_0D), .INIT_RAM_0E(DSD_B4_0E),
        .INIT_RAM_0F(DSD_B4_0F)
    ) cb4 (
        .DO(csel4), .DI(32'd0), .BLKSELA(3'd0), .BLKSELB(3'd0),
        .ADA(14'd0), .ADB(ram_b),
        .CLKA(mclk), .CLKB(mclk), .CEA(1'b0), .CEB(1'b1),
        .OCE(1'b1), .RESET(1'b0)
    );

    SDPB #(
        .INIT_RAM_00(DSD_B5_00), .INIT_RAM_01(DSD_B5_01), .INIT_RAM_02(DSD_B5_02),
        .INIT_RAM_03(DSD_B5_03), .INIT_RAM_04(DSD_B5_04), .INIT_RAM_05(DSD_B5_05),
        .INIT_RAM_06(DSD_B5_06), .INIT_RAM_07(DSD_B5_07), .INIT_RAM_08(DSD_B5_08),
        .INIT_RAM_09(DSD_B5_09), .INIT_RAM_0A(DSD_B5_0A), .INIT_RAM_0B(DSD_B5_0B),
        .INIT_RAM_0C(DSD_B5_0C), .INIT_RAM_0D(DSD_B5_0D), .INIT_RAM_0E(DSD_B5_0E),
        .INIT_RAM_0F(DSD_B5_0F)
    ) cb5 (
        .DO(csel5), .DI(32'd0), .BLKSELA(3'd0), .BLKSELB(3'd0),
        .ADA(14'd0), .ADB(ram_b),
        .CLKA(mclk), .CLKB(mclk), .CEA(1'b0), .CEB(1'b1),
        .OCE(1'b1), .RESET(1'b0)
    );

    SDPB #(
        .INIT_RAM_00(DSD_B6_00), .INIT_RAM_01(DSD_B6_01), .INIT_RAM_02(DSD_B6_02),
        .INIT_RAM_03(DSD_B6_03), .INIT_RAM_04(DSD_B6_04), .INIT_RAM_05(DSD_B6_05),
        .INIT_RAM_06(DSD_B6_06), .INIT_RAM_07(DSD_B6_07), .INIT_RAM_08(DSD_B6_08),
        .INIT_RAM_09(DSD_B6_09), .INIT_RAM_0A(DSD_B6_0A), .INIT_RAM_0B(DSD_B6_0B),
        .INIT_RAM_0C(DSD_B6_0C), .INIT_RAM_0D(DSD_B6_0D), .INIT_RAM_0E(DSD_B6_0E),
        .INIT_RAM_0F(DSD_B6_0F)
    ) cb6 (
        .DO(csel6), .DI(32'd0), .BLKSELA(3'd0), .BLKSELB(3'd0),
        .ADA(14'd0), .ADB(ram_b),
        .CLKA(mclk), .CLKB(mclk), .CEA(1'b0), .CEB(1'b1),
        .OCE(1'b1), .RESET(1'b0)
    );

    SDPB #(
        .INIT_RAM_00(DSD_B7_00), .INIT_RAM_01(DSD_B7_01), .INIT_RAM_02(DSD_B7_02),
        .INIT_RAM_03(DSD_B7_03), .INIT_RAM_04(DSD_B7_04), .INIT_RAM_05(DSD_B7_05),
        .INIT_RAM_06(DSD_B7_06), .INIT_RAM_07(DSD_B7_07), .INIT_RAM_08(DSD_B7_08),
        .INIT_RAM_09(DSD_B7_09), .INIT_RAM_0A(DSD_B7_0A), .INIT_RAM_0B(DSD_B7_0B),
        .INIT_RAM_0C(DSD_B7_0C), .INIT_RAM_0D(DSD_B7_0D), .INIT_RAM_0E(DSD_B7_0E),
        .INIT_RAM_0F(DSD_B7_0F)
    ) cb7 (
        .DO(csel7), .DI(32'd0), .BLKSELA(3'd0), .BLKSELB(3'd0),
        .ADA(14'd0), .ADB(ram_b),
        .CLKA(mclk), .CLKB(mclk), .CEA(1'b0), .CEB(1'b1),
        .OCE(1'b1), .RESET(1'b0)
    );

    // ---------------- FIR: 8 add/sub taps per MCLK per channel ----------------
    // The RAM outputs registered this cycle hold the coefficients for the
    // taps tap_base..tap_base+7, matching the 1-cycle read latency.
    //
    // Two pipeline stages with a register in between. The register is what
    // actually breaks the long combinational path: Gowin synthesis rebuilds
    // a sequential adder chain from ANY parenthesized 8-term sum, so a
    // balanced tree alone changes nothing (measured: identical 22.9 ns
    // worst path before and after re-parenthesizing). Stage 1 registers the
    // 8 muxed tap terms; stage 2 accumulates the previous group through a
    // 3-level adder tree. Bit-identical result: 8 x 32-bit terms fit in
    // 44 bits with no intermediate truncation.
    reg signed [43:0] t_l0, t_l1, t_l2, t_l3, t_l4, t_l5, t_l6, t_l7;
    reg signed [43:0] t_r0, t_r1, t_r2, t_r3, t_r4, t_r5, t_r6, t_r7;
    reg signed [43:0] sum_l;
    reg signed [43:0] sum_r;
    reg signed [43:0] out_sum_l;
    reg signed [43:0] out_sum_r;
    reg        valid_int;

    wire signed [43:0] group_sum_l =
        ((t_l0 + t_l1) + (t_l2 + t_l3)) + ((t_l4 + t_l5) + (t_l6 + t_l7));
    wire signed [43:0] group_sum_r =
        ((t_r0 + t_r1) + (t_r2 + t_r3)) + ((t_r4 + t_r5) + (t_r6 + t_r7));

    always @(posedge mclk or negedge rst_n) begin
        if (!rst_n) begin
            tapk <= 7'd0;
            tap_base <= 10'd0;
            fir_sr_l <= {TAPS{1'b0}};
            fir_sr_r <= {TAPS{1'b0}};
            t_l0 <= 44'sd0; t_l1 <= 44'sd0; t_l2 <= 44'sd0; t_l3 <= 44'sd0;
            t_l4 <= 44'sd0; t_l5 <= 44'sd0; t_l6 <= 44'sd0; t_l7 <= 44'sd0;
            t_r0 <= 44'sd0; t_r1 <= 44'sd0; t_r2 <= 44'sd0; t_r3 <= 44'sd0;
            t_r4 <= 44'sd0; t_r5 <= 44'sd0; t_r6 <= 44'sd0; t_r7 <= 44'sd0;
            sum_l <= 44'sd0;
            sum_r <= 44'sd0;
            out_sum_l <= 44'sd0;
            out_sum_r <= 44'sd0;
            valid_int <= 1'b0;
        end else begin
            tap_base <= {tapk, 3'd0};

            // Stage 1: mux the 8 terms of the current group into registers.
            t_l0 <= fir_sr_l[tap_base + 3'd0] ? $signed(csel0) : -$signed(csel0);
            t_l1 <= fir_sr_l[tap_base + 3'd1] ? $signed(csel1) : -$signed(csel1);
            t_l2 <= fir_sr_l[tap_base + 3'd2] ? $signed(csel2) : -$signed(csel2);
            t_l3 <= fir_sr_l[tap_base + 3'd3] ? $signed(csel3) : -$signed(csel3);
            t_l4 <= fir_sr_l[tap_base + 3'd4] ? $signed(csel4) : -$signed(csel4);
            t_l5 <= fir_sr_l[tap_base + 3'd5] ? $signed(csel5) : -$signed(csel5);
            t_l6 <= fir_sr_l[tap_base + 3'd6] ? $signed(csel6) : -$signed(csel6);
            t_l7 <= fir_sr_l[tap_base + 3'd7] ? $signed(csel7) : -$signed(csel7);
            t_r0 <= fir_sr_r[tap_base + 3'd0] ? $signed(csel0) : -$signed(csel0);
            t_r1 <= fir_sr_r[tap_base + 3'd1] ? $signed(csel1) : -$signed(csel1);
            t_r2 <= fir_sr_r[tap_base + 3'd2] ? $signed(csel2) : -$signed(csel2);
            t_r3 <= fir_sr_r[tap_base + 3'd3] ? $signed(csel3) : -$signed(csel3);
            t_r4 <= fir_sr_r[tap_base + 3'd4] ? $signed(csel4) : -$signed(csel4);
            t_r5 <= fir_sr_r[tap_base + 3'd5] ? $signed(csel5) : -$signed(csel5);
            t_r6 <= fir_sr_r[tap_base + 3'd6] ? $signed(csel6) : -$signed(csel6);
            t_r7 <= fir_sr_r[tap_base + 3'd7] ? $signed(csel7) : -$signed(csel7);

            // Stage 2: accumulate the previous group's registered terms.
            // tapk lag: the mux processes group tapk-1 and the sum
            // processes group tapk-2, so the lap boundary sits at tapk 1/2.
            if (tapk == 7'd0) begin
                // Sum adds group 126; snapshot the live delay line for the
                // next lap. Group 127 of THIS lap is still muxed from the
                // old snapshot in this same cycle (nonblocking order).
                sum_l <= sum_l + group_sum_l;
                sum_r <= sum_r + group_sum_r;
                fir_sr_l <= sr_l;
                fir_sr_r <= sr_r;
            end else if (tapk == 7'd1) begin
                // Group 127 completes the 1024-tap sum.
                sum_l <= sum_l + group_sum_l;
                sum_r <= sum_r + group_sum_r;
            end else if (tapk == 7'd2) begin
                // Capture the completed lap, restart with group 0.
                out_sum_l <= sum_l;
                out_sum_r <= sum_r;
                sum_l <= group_sum_l;
                sum_r <= group_sum_r;
            end else begin
                sum_l <= sum_l + group_sum_l;
                sum_r <= sum_r + group_sum_r;
            end

            valid_int <= (tapk == 7'd2) && decide_done;

            if (tapk == 7'd127)
                tapk <= 7'd0;
            else
                tapk <= tapk + 7'd1;
        end
    end

    // ---------------- output latch with saturation ----------------
    always @(posedge mclk or negedge rst_n) begin
        if (!rst_n) begin
            sample_valid <= 1'b0;
            sample_l <= 32'sd0;
            sample_r <= 32'sd0;
        end else begin
            sample_valid <= valid_int;
            if (out_sum_l > 44'sd2147483647)
                sample_l <= 32'sh7fffffff;
            else if (out_sum_l < -44'sd2147483648)
                sample_l <= 32'sh80000000;
            else
                sample_l <= out_sum_l[31:0];
            if (out_sum_r > 44'sd2147483647)
                sample_r <= 32'sh7fffffff;
            else if (out_sum_r < -44'sd2147483648)
                sample_r <= 32'sh80000000;
            else
                sample_r <= out_sum_r[31:0];
        end
    end

endmodule
